src/objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Agent</label>
        <referenceTo>Sales_Agent__c</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Agent__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Pending__c</fullName>
        <label>Amount Pending</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sales Agent</label>
    <nameField>
        <label>Sales Agent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CommissionsSelector.cls
/**
 * CommissionsSelector - Selector class for Commission__c object
 * @author Juan Vaz
 */
public with sharing class CommissionsSelector {

    /**
     * Retrieves the Commissions list filtered by 
     * sales agent ids and opportunity stage
     * @param  salesAgentIds Sales Agents id list
     * @param  opptyStage    Filter for Opportunity Satge
     * @return               returns the Commissions list filtered by 
     *                      sales agent ids and opportunity stage
     */ 
    public List<Commission__c> getCommissionsByAgentsAndOpptyStage(List<Id> salesAgentIds, String opptyStage){

        if (salesAgentIds != null && !salesAgentIds.isEmpty()) {

            String query =  'SELECT id, Sales_Agent__c, Sales_Agent__r.Amount_Pending__c, Opportunity__c, Opportunity__r.Stage__c, Opportunity__r.Amount__c '+
                            'FROM Commission__c '+
                            'WHERE Sales_Agent__c in: salesAgentIds';

            if(String.isNotBlank(opptyStage)){
                query += ' AND Opportunity__r.Stage__c =: opptyStage';
            }                        

            return Database.query(query);

        }

        return null;

    }

    /**
     * Retrieves the Commissions list filtered by opp ids
     * @param  opportunityIds opportunities id list
     * @return               returns the Commissions list filtered by 
     *                      opportunity ids
     */ 
    public List<Commission__c> getCommissionsByOpportunities(List<Id> opportunityIds){

        if (opportunityIds != null && !opportunityIds.isEmpty()) {

            String query =  'SELECT id, Sales_Agent__c, Sales_Agent__r.Amount_Pending__c, Opportunity__c, Opportunity__r.Stage__c, Opportunity__r.Amount__c '+
                            'FROM Commission__c WHERE Opportunity__c in: opportunityIds';

            return Database.query(query);

        }

        return null;

    }

}