src/objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Agent</label>
        <referenceTo>Sales_Agent__c</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Agent__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Pending__c</fullName>
        <label>Amount Pending</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sales Agent</label>
    <nameField>
        <label>Sales Agent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CommissionsService.cls
/**
 * CommissionsService
 * Service class 
 * @author Juan Vaz
 */
public with sharing class CommissionsService {

    public static final String NEW_OPPORTUNITY_STAGE = 'New';
    public static final String PENDING_OPPORTUNITY_STAGE = 'Pending';

    public void updateSalesAgentsPendingCommissions(List<Id> salesAgentIds){
        List<Commission__c> agentPendingCommissions = 
                new CommissionsSelector().getCommissionsByAgentsAndOpptyStage(salesAgentIds, PENDING_OPPORTUNITY_STAGE);
        
        if(agentPendingCommissions != null && !agentPendingCommissions.isEmpty()){
            // calculate the commissions amount for the agents involved
            Map<Id, Decimal> agentCommissionsMap = new Commissions(agentPendingCommissions).calculateCommissions();

            List<Sales_Agent__c> agentsToUpdate = new List<Sales_Agent__c>();

            for(Id agentId : agentCommissionsMap.keySet()){
                agentsToUpdate.add(
                    new Sales_Agent__c(
                        Id = agentId, 
                        Amount_Pending__c = agentCommissionsMap.get(agentId)
                    )
                );
            }

            update agentsToUpdate;
        }
        
    }

}