src/objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Agent</label>
        <referenceTo>Sales_Agent__c</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Agent__c.object
<CustomObject>
    <label>Sales Agent</label>
    <nameField>
        <label>Sales Agent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Commissions.cls
/**
 * Domains Layer class for Commission__c sObject
 */
public with sharing class Commissions {

    @TestVisible List<Commission__c> records;
    
    public Commissions(){
        this.records = new List<Commission__c>();
    }

    public Commissions(List<Commission__c> comms){
        this.records = comms;
    }

    /**
     * Calculates the Sales Agent Commissions for all records 
     * @return returns a Map from Sales Agent Id to Commissions Amount
     */ 
    public Map<Id, Decimal> calculateCommissions(){
        Map<Id, Decimal> agentCommissionsMap = new Map<Id, Decimal>();
        if(this.records != null){
            for(Commission__c comm : records){

                if(comm.Opportunity__r != null && comm.Opportunity__r.Amount__c != null){
                    Decimal commissionAmount = 0;
                    if(agentCommissionsMap.containsKey(comm.Sales_Agent__c)){
                        commissionAmount = agentCommissionsMap.get(comm.Sales_Agent__c);
                    }
                    agentCommissionsMap.put(comm.Sales_Agent__c, 
                            commissionAmount + comm.Opportunity__r.Amount__c);

                }
            }
        }
        return agentCommissionsMap;        
    }

    /**
     * After Insert trigger event handler
     * Updates all related sales agents commissions
     * for every inserted Commission having a pending associated oppty
     */
    public void onAfterInsert(){

    }

    /**
     * After Update trigger event handler
     * Updates all related sales agents commissions
     * for every Commission having opportunity changed from/to a pending oppty
     * or having the sales agent changed and a pending associated oppty
     * @param  oldMap Trigger old map
     */
    public void onAfterUpdate(List<Commission__c> oldRecords){
        
    }
    
    /**
     * After Delete trigger event handler
     * Updates all related sales agents commissions
     * for every deleted Commission having a pending associated oppty
     */
    public void onAfterDelete(){

    }

}