src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunitiesSelector.cls
/**
 * OpportunitiesSelector - Selector class for Opportunity object
 * @author Juan Vaz
 */
public with sharing class OpportunitiesSelector {

    /**
     * Retrieves all the Opportunities filtered by stage
     * @param stage opportunity stage
     * @return list of opportunites having the stage passed in
     */
    public List<Opportunity> getOpportunitiesByStage(String stage){
        String query =  'SELECT id, Stage__c, Amount__c '+
                        'FROM Opportunity ';
                        
        if(String.isNotBlank(stage)){
            query += ' WHERE Stage__c =: stage';
        }                        

        return Database.query(query);
    }

}